// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createUser.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (UserID, FirstName, Email, HashedPassword)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
)
RETURNING userid, firstname, email, hashedpassword
`

type CreateUserParams struct {
	Firstname      string `json:"firstname"`
	Email          string `json:"email"`
	Hashedpassword string `json:"hashedpassword"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Firstname, arg.Email, arg.Hashedpassword)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Firstname,
		&i.Email,
		&i.Hashedpassword,
	)
	return i, err
}
