// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type User struct {
	Userid         string    `json:"userid"`
	Firstname      string    `json:"firstname"`
	Email          string    `json:"email"`
	Hashedpassword string    `json:"hashedpassword"`
	Createdat      time.Time `json:"createdat"`
	Lastedit       time.Time `json:"lastedit"`
}
