-- +goose Up
ALTER TABLE users
ADD COLUMN CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
ADD COLUMN LastEdit TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- +goose Down
ALTER TABLE users
DROP COLUMN CreatedAt, 
DROP COLUMN LastEdit;